name: On Merge to Main

on:
  push:
    branches: [main]

jobs:
  update-queries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necessary to get a complete history for diff

      - name: Install necessary tools
        run: sudo apt-get install -y jq # Installing jq for JSON processing

      - name: Get list of changed files in a specific directory
        id: get-changed-files
        run: |
          # Replace 'your/specific/directory/' with the path to your directory
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- queries | paste -sd "," -)
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
          echo "::set-output name=changed_files::$CHANGED_FILES"

      - name: Update Queries
        uses: bh2smith/dune-update@v0.0.0-beta
        with:
          changedQueries: $CHANGED_FILES
          duneApiKey: ${{ secrets.DUNE_API_KEY }}
